//--------------------------------------------------------------------------------------------------------
// Botany

// Soil
recipes.addShapeless(<Botany:soil:7> * 4, [<terrafirmacraft:Grass:*>, <terrafirmacraft:Grass:*>, <terrafirmacraft:Grass:*>, <terrafirmacraft:Grass:*>]);

// Trowels
recipes.remove(<Botany:trowelDiamond>);
recipes.remove(<Botany:trowelWood>);
recipes.remove(<Botany:trowelStone>);
mods.forestry.Carpenter.addRecipe(<Botany:trowelStone>,
	[[<Botany:soil:*> ,null,null],
	 [null,<ore:ingotIron>,null],
	 [null,null,<ore:itemRock>]]
	, <liquid:seedoil> * 200, 1000, <Forestry:pollen>);
recipes.remove(<Botany:trowelIron>);
mods.forestry.Carpenter.addRecipe(<Botany:trowelIron>,
	[[<Botany:soil:*> ,null,null],
	 [null,<ore:ingotIron>,null],
	 [null,null,<ore:stickWood>]]
	, <liquid:seedoil> * 200, 1000, <Forestry:pollen>);	
recipes.remove(<Botany:trowelGold>);
mods.forestry.Carpenter.addRecipe(<Botany:trowelGold>,
	[[<Botany:soil:*> ,null,null],
	 [null,<ore:ingotGold>,null],
	 [null,null,<ore:stickWood>]]
	, <liquid:seedoil> * 200, 1000, <Forestry:pollen>);	

// Flowers
for item in <Botany:trowelGold>.items {
//recipes.addShapeless(<minecraft:yellow_flower>, [<terrafirmacraft:Flowers>]);
recipes.addShapeless(<minecraft:yellow_flower>, [<terrafirmacraft:Flowers>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower>, [<terrafirmacraft:Flowers2>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:1>, [<terrafirmacraft:Flowers2:1>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:2>, [<terrafirmacraft:Flowers2:2>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:3>, [<terrafirmacraft:Flowers2:3>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:4>, [<terrafirmacraft:Flowers2:4>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:5>, [<terrafirmacraft:Flowers2:5>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:6>, [<terrafirmacraft:Flowers2:6>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:7>, [<terrafirmacraft:Flowers2:7>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
recipes.addShapeless(<minecraft:red_flower:8>, [<terrafirmacraft:Flowers2:8>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.dandelion", UID0: "botany.flowers.species.dandelion", Slot: 0 as byte}, {UID1: "botany.colorYellow", UID0: "botany.colorYellow", Slot: 1 as byte}, {UID1: "botany.colorYellow", UID0: "botany.colorYellow", Slot: 2 as byte}, {UID1: "forestry.fertilityHigh", UID0: "forestry.fertilityHigh", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanShortened", UID0: "forestry.lifespanShortened", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 9 as byte}, {UID1: "forestry.sappinessLower", UID0: "forestry.sappinessLower", Slot: 10 as byte}, {UID1: "botany.colorGreen", UID0: "botany.colorGreen", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.poppy", UID0: "botany.flowers.species.poppy", Slot: 0 as byte}, {UID1: "botany.colorRed", UID0: "botany.colorRed", Slot: 1 as byte}, {UID1: "botany.colorRed", UID0: "botany.colorRed", Slot: 2 as byte}, {UID1: "forestry.fertilityHigh", UID0: "forestry.fertilityHigh", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth2", UID0: "forestry.toleranceBoth2", Slot: 7 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 8 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 9 as byte}, {UID1: "forestry.sappinessAverage", UID0: "forestry.sappinessAverage", Slot: 10 as byte}, {UID1: "botany.colorGreen", UID0: "botany.colorGreen", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.orchid", UID0: "botany.flowers.species.orchid", Slot: 0 as byte}, {UID1: "botany.colorDeepSkyBlue", UID0: "botany.colorDeepSkyBlue", Slot: 1 as byte}, {UID1: "botany.colorDeepSkyBlue", UID0: "botany.colorDeepSkyBlue", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanLong", UID0: "forestry.lifespanLong", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 9 as byte}, {UID1: "forestry.sappinessLow", UID0: "forestry.sappinessLow", Slot: 10 as byte}, {UID1: "botany.colorGreen", UID0: "botany.colorGreen", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:1>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.allium", UID0: "botany.flowers.species.allium", Slot: 0 as byte}, {UID1: "botany.colorMediumPurple", UID0: "botany.colorMediumPurple", Slot: 1 as byte}, {UID1: "botany.colorMediumPurple", UID0: "botany.colorMediumPurple", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanNormal", UID0: "forestry.lifespanNormal", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 8 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 9 as byte}, {UID1: "forestry.sappinessLow", UID0: "forestry.sappinessLow", Slot: 10 as byte}, {UID1: "botany.colorGreen", UID0: "botany.colorGreen", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:2>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.bluet", UID0: "botany.flowers.species.bluet", Slot: 0 as byte}, {UID1: "botany.colorLavender", UID0: "botany.colorLavender", Slot: 1 as byte}, {UID1: "botany.colorKhaki", UID0: "botany.colorKhaki", Slot: 2 as byte}, {UID1: "forestry.fertilityLow", UID0: "forestry.fertilityLow", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanNormal", UID0: "forestry.lifespanNormal", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 8 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 9 as byte}, {UID1: "forestry.sappinessLower", UID0: "forestry.sappinessLower", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:3>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.tulip", UID0: "botany.flowers.species.tulip", Slot: 0 as byte}, {UID1: "botany.colorCrimson", UID0: "botany.colorCrimson", Slot: 1 as byte}, {UID1: "botany.colorCrimson", UID0: "botany.colorCrimson", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanLong", UID0: "forestry.lifespanLong", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 9 as byte}, {UID1: "forestry.sappinessAverage", UID0: "forestry.sappinessAverage", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:4>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.tulip", UID0: "botany.flowers.species.tulip", Slot: 0 as byte}, {UID1: "botany.colorDarkOrange", UID0: "botany.colorDarkOrange", Slot: 1 as byte}, {UID1: "botany.colorDarkOrange", UID0: "botany.colorDarkOrange", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanLong", UID0: "forestry.lifespanLong", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 9 as byte}, {UID1: "forestry.sappinessAverage", UID0: "forestry.sappinessAverage", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:5>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.tulip", UID0: "botany.flowers.species.tulip", Slot: 0 as byte}, {UID1: "botany.colorWhite", UID0: "botany.colorWhite", Slot: 1 as byte}, {UID1: "botany.colorWhite", UID0: "botany.colorWhite", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanLong", UID0: "forestry.lifespanLong", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 9 as byte}, {UID1: "forestry.sappinessAverage", UID0: "forestry.sappinessAverage", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:6>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.tulip", UID0: "botany.flowers.species.tulip", Slot: 0 as byte}, {UID1: "botany.colorViolet", UID0: "botany.colorViolet", Slot: 1 as byte}, {UID1: "botany.colorViolet", UID0: "botany.colorViolet", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanLong", UID0: "forestry.lifespanLong", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 7 as byte}, {UID1: "forestry.toleranceBoth1", UID0: "forestry.toleranceBoth1", Slot: 8 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 9 as byte}, {UID1: "forestry.sappinessAverage", UID0: "forestry.sappinessAverage", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:7>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
//recipes.addShapeless(<Botany:itemFlower>.withTag({Wilt: 0 as byte, Flowered: 1 as byte, IsAnalyzed: 0 as byte, Genome: {Chromosomes: [{UID1: "botany.flowers.species.daisy", UID0: "botany.flowers.species.daisy", Slot: 0 as byte}, {UID1: "botany.colorWhite", UID0: "botany.colorWhite", Slot: 1 as byte}, {UID1: "botany.colorYellow", UID0: "botany.colorYellow", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 4 as byte}, {UID1: "binnie.flowerEffectNone", UID0: "binnie.flowerEffectNone", Slot: 5 as byte}, {UID1: "forestry.lifespanNormal", UID0: "forestry.lifespanNormal", Slot: 6 as byte}, {UID1: "forestry.toleranceBoth2", UID0: "forestry.toleranceBoth2", Slot: 7 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 8 as byte}, {UID1: "forestry.toleranceDown1", UID0: "forestry.toleranceDown1", Slot: 9 as byte}, {UID1: "forestry.sappinessLow", UID0: "forestry.sappinessLow", Slot: 10 as byte}, {UID1: "botany.colorOliveDrab", UID0: "botany.colorOliveDrab", Slot: 11 as byte}]}, Age: 2}), [<terrafirmacraft:Flowers2:8>, <Forestry:pollen>, item.anyDamage().transformDamage(1) ]);
}
